🐛 - Support non-coroutine handler properly
ysk24ok/dd-trace-py pull request #2
Opened 2022-02-19 13:14 UTC by isac322

As I described [here](https://github.com/ysk24ok/dd-trace-py/pull/1#issuecomment-1044596806). You should not wrap sync handler within async interceptor.

- Create `_TracedRpcMethodHandler` in `aio_server_interceptor.py`
- Extract `_create_span` from `_TracedAioRpcMethodHandler` to share with `_TracedRpcMethodHandler`
- Rename `_wrap_*_response` to `_wrap_aio_*_response` and create sync versions
- Create `_handle_server_exception`
  - I found that `servicer_context` contains `details` and `code` for aborted request
- Assert that methods of `_SyncHelloServicer` are not invoked in async context on unit test

2022-02-22 10:50 UTC, ysk24ok requested changes
Thank you for the PR.

But it seems the following tests are flaky and they often hang up or fail the assertion. Could you take a look?
- `test_server_streaming_exception[_SyncHelloServicer]`
- `test_server_streaming_cancelled_during_rpc[_SyncHelloServicer]`
- `test_bidi_streaming_cancelled_during_rpc[_SyncHelloServicer]`

You can run tests locally.

```console
$ scripts/ddtest  # start a container
# riot run -s grpc_aio
```

2022-02-22 10:50 UTC, ysk24ok commented on ddtrace/contrib/grpc_aio/aio_server_interceptor.py
> +    server_context,  # type: Union[None, grpc.ServicerContext]
This var name should be `servicer_context` because this is an instance of `grpc.ServicerContext`.

2022-02-22 10:50 UTC, ysk24ok commented on ddtrace/contrib/grpc_aio/aio_server_interceptor.py
> +    # type: (...) -> RequestIterableType
`ResponseIterableType` is correct.

2022-02-22 10:50 UTC, ysk24ok commented on tests/contrib/grpc_aio/test_grpc_aio.py
> +async def test_pin_tags_put_in_span(patch_grpc_aio, servicer, tracer):
```suggestion
async def test_pin_tags_put_in_span(servicer, tracer):
```

Now that `autouse=True`, no need to pass `patch_grpc_aio`.

2022-02-22 10:50 UTC, ysk24ok commented on tests/contrib/grpc_aio/test_grpc_aio.py
> +    yield _ServerInfo(target, abort_supported)
Due to these changes, developers need to access `servicer.target` to get `target` to pass to `grpc.aio.channel`.
IMO It's strange that `servicer` fixture has `target` property.
You should align the fixture name and its yielded value.

2022-02-22 10:50 UTC, ysk24ok commented on tests/contrib/grpc_aio/test_grpc_aio.py
> +def event_loop():
Why is this fixture needed?
Confirmed deleting this fixture doesn't lead to tests failure.

2022-03-01 11:19 UTC, ysk24ok commented
@isac322 Hello, have you worked on the fix? If not, I will.

> test_server_streaming_exception[_SyncHelloServicer]
> test_server_streaming_cancelled_during_rpc[_SyncHelloServicer]
> test_bidi_streaming_cancelled_during_rpc[_SyncHelloServicer]

As for these three cases, I'm thinking of deleting them.
They might be a bug in grpc itself and I'd rather not to spend too much time on them.

2022-03-03 11:29 UTC, ysk24ok commented on tests/contrib/grpc_aio/test_grpc_aio.py
> +    yield _ServerInfo(target, abort_supported)
Fixed in b5b24cd.

2022-03-03 11:31 UTC, ysk24ok commented on tests/contrib/grpc_aio/test_grpc_aio.py
> +async def test_pin_tags_put_in_span(patch_grpc_aio, servicer, tracer):
Fixed in da5c6fa.

2022-03-03 11:31 UTC, ysk24ok commented on tests/contrib/grpc_aio/test_grpc_aio.py
> +def event_loop():
Deleted in 2ae677d.

2022-03-03 11:39 UTC, ysk24ok commented on ddtrace/contrib/grpc_aio/aio_server_interceptor.py
> +    server_context,  # type: Union[None, grpc.ServicerContext]
Fixed in 75b9019.

2022-03-03 11:42 UTC, ysk24ok commented on ddtrace/contrib/grpc_aio/aio_server_interceptor.py
> +    # type: (...) -> RequestIterableType
Fixed in 38cdef4.

2022-03-03 11:43 UTC, ysk24ok commented
@isac322 Pushed several commits. Could you take a look before merge?

2022-03-04 16:48 UTC, isac322 commented
@ysk24ok Thanks for your work. LGTM!

2022-03-05 13:19 UTC, merged